mqtt_bridge_node:
  ros__parameters:
    mqtt:
      client:
        protocol: 4      # MQTTv311
      connection:
        host: "localhost"
        port: 1883
        keepalive: 60
      private_path: "cmeresearch/cmexaiii-001"
    serializer: json:dumps
    deserializer: json:loads
    n_bridges: 5
    bridge:
      bridge1: ["mqtt_bridge.bridge:RosToMqttBridge","geometry_msgs.msg:TwistStamped","/base_mecanum_controller/cmd_vel","~/base/cmd_vel"]
      bridge2: ["mqtt_bridge.bridge:RosToMqttBridge","cmeresearch_msgs.msg:TinkerStepperCommand","/cmexaiii/front_left/cmd_vel","~/base/front_left/cmd_vel"]
      bridge3: ["mqtt_bridge.bridge:RosToMqttBridge","nav_msgs.msg:Odometry","/base_mecanum_controller/odometry","~/base/odometry"]
      bridge4: ["mqtt_bridge.bridge:RosToMqttBridge","cmeresearch_msgs.msg:RobotState","/robot_state","~/robot_state"]
      bridge5: ["mqtt_bridge.bridge:MqttToRosBridge","std_msgs.msg:String","~/robot_cmd","/robot_cmd"]