ros__parameters:
  broker:
    host: localhost
    port: 1883
  bridge:
    ros2mqtt:
      ros_topics:
        - /cmexa_base_mecanum_controller/cmd_vel
      /cmexa_base_mecanum_controller/cmd_vel:
        mqtt_topic: cmeresearch/cmexa/amr_control/cmd_vel
    mqtt2ros:
      mqtt_topics:
        - cmeresearch/cmexa/amr_control/cmd_vel
      cmeresearch/cmexa/amr_control/cmd_vel:
        ros_topic: /cmexa_base_mecanum_controller/cmd_vel